name: Automation Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Get Next Version
        uses: reecetech/version-increment@2023.9.3
        id: version_increment
        with:
          scheme: semver
          increment: patch

      - name: Tag Version To Use
        run: echo "${{ steps.version_increment.outputs.version }}"

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.version_increment.outputs.version }}
          git push origin ${{ steps.version_increment.outputs.version }}
  
