name: Automation Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Get Next Version
        uses: reecetech/version-increment@2023.9.3
        id: version_increment
        with:
          scheme: semver
          increment: patch

      - name: Tag Version To Use
        run: echo "${{ steps.version_increment.outputs.version }}"

      - name: Auto Tag
        uses: butlerlogic/action-autotag@1.0.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: "${{ steps.version_increment.outputs.version }}"
